
enabled_layouts tall:bias=50;full_size=1;mirrored=false

window_padding_width 0

editor nvim

font_size 12
# font_family      family="Monaspace Krypton"
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# font_family Hack

open_url_with default
detect_urls yes
tab_bar_style hidden

copy_on_select yes

background_opacity 0.9
background_image_layout scaled
dynamic_background_opacity yes


hide_window_decorations yes

disable_ligatures always
/* disable_ligatures never */

# gruvbox dark by morhetz, https://github.com/morhetz/gruvbox
# This work is licensed under the terms of the MIT license.
# For a copy, see https://opensource.org/licenses/MIT.

# Colors

# A port of forest night by sainnhe
# https://github.com/sainnhe/forest-night

# Based on https://github.com/morhetz/gruvbox by morhetz <morhetz@gmail.com>
# Adapted to kitty by wdomitrz <witekdomitrz@gmail.com>

# Emerald Matrix - A green accent theme for Kitty terminal

# The basic colors
# The basic colors
foreground            #abb2bf
background            #000000
selection_foreground  #abb2bf
selection_background  #212121
# Cursor colors
cursor                #e2be7d
cursor_text_color     #000000
# URL underline color when hovering
url_color             #61afef
# Window border colors
active_border_color   #89ca78
inactive_border_color #434852
# Tab bar colors
active_tab_foreground   #000000
active_tab_background   #89ca78
inactive_tab_foreground #abb2bf
inactive_tab_background #434852
# The 16 terminal colors
# black
color0   #000000
color8   #434852
# red
color1   #ef596f
color9   #ef596f
# green
color2   #89ca78
color10  #109868
# yellow
color3   #e5c07b
color11  #d19a66
# blue
color4   #61afef
color12  #90c7f4
# magenta
color5   #d55fde
color13  #d55fde
# cyan
color6   #2bbac5
color14  #4fcfd8
# white
color7   #abb2bf
color15  #abb2bf
# Marks
mark1_foreground #000000
mark1_background #89ca78
mark2_foreground #000000
mark2_background #2bbac5
mark3_foreground #000000
mark3_background #e5c07b
# Hints
hint_foreground #000000
hint_background #89ca78

# BEGIN_KITTY_FONTS
font_family      family="Hack"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
